<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhmsBPH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhmsBPH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFhmsBPH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFhmsBPH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFhmsBPH\App_KernelDevDebugContainer([
    'container.build_hash' => 'FhmsBPH',
    'container.build_id' => 'a7d13264',
    'container.build_time' => 1588512728,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhmsBPH');
