<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAIx8Ptq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAIx8Ptq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAIx8Ptq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAIx8Ptq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAIx8Ptq\App_KernelDevDebugContainer([
    'container.build_hash' => 'AIx8Ptq',
    'container.build_id' => '8747ae15',
    'container.build_time' => 1588511732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAIx8Ptq');
