<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Mf0Luu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Mf0Luu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Mf0Luu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Mf0Luu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3Mf0Luu\App_KernelDevDebugContainer([
    'container.build_hash' => '3Mf0Luu',
    'container.build_id' => '87ba173a',
    'container.build_time' => 1588513190,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Mf0Luu');
